import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {RECIPES_DIR,runtimeModuleUrl} from '../lib/dsh-paths.mjs';
const {assertObjectJsonSchema,validateJsonSchemaValue}=await import(runtimeModuleUrl('@deepseek-ai/dsh-tools'));
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
const dir=path.join(RECIPES_DIR,'investigate');
const scope=()=>({files:['src/a.js'],summary:'Source-only scope',complete:true,limitations:[]});
const hypothesis=(id='local')=>({id,cause:'Missing validation',file:'src/a.js',line:3,evidence:'input goes unchecked',confidence:0.8});
const gather=()=>({hypotheses:[hypothesis()],coverage:['src/a.js'],complete:true,limitations:[]});
const resolution=(id='H1',status='confirmed')=>({id,status,reason:'Source establishes flow',evidence:'src/a.js:3 direct input flow',confidence:0.9});
const check=()=>({resolutions:[resolution()],coverage:['src/a.js'],complete:true,limitations:[],next_actions:['Hand confirmed source defect to bug-fix for runtime reproduction']});
async function run(overrides={},args={}){
 const source=await readFile(path.join(dir,'script.js'),'utf8');const fn=new AsyncFunction('agent','parallel','phase','log','args',source);const calls=[];
 const defaults={scope:scope(),gather:gather(),check:check()};
 const agent=async(prompt,opts)=>{assert.deepEqual(Object.keys(opts).sort(),['label','phase','schema']);assertObjectJsonSchema(opts.schema);calls.push({prompt,...opts});let v=Object.hasOwn(overrides,opts.label)?overrides[opts.label]:defaults[opts.label];if(typeof v==='function')v=await v(prompt,opts);if(v!=null)calls[calls.length-1].violations=validateJsonSchemaValue(opts.schema,v);return structuredClone(v);};
 return {result:await fn(agent,h=>Promise.all(h.map(f=>Promise.resolve().then(f).catch(()=>null))),()=>{},()=>{},{task:'Investigate bad input',repo:'/repo',routingToken:'token',...args}),calls};
}
test('saved metadata uses a medium scope role and strong investigation roles',async()=>{const m=JSON.parse(await readFile(path.join(dir,'meta.json'),'utf8'));assert.equal(m.name,'investigate');assert.equal(m.roles['investigation-scope'].tier,'medium');assert.equal(m.roles.investigator.tier,'strong');assert.equal(m.roles['investigation-checker'].tier,'strong');assert.equal(m.phases.length,3);});
for(const status of ['confirmed','rejected','inconclusive'])test('source verdict never certifies runtime cause '+status,async()=>{
 const {result,calls}=await run({check:{...check(),resolutions:[resolution('H1',status)]}});
 assert.equal(result.cause_status,status);
 assert.equal(result.evidence_kind,'source_only');
 assert.equal(result.runtime_verified,false);
 assert.match(result.summary,/Runtime cause remains unverified/);
 assert.match(calls.find(c=>c.label==='check').prompt,/unobserved runtime inputs, ordering, environment/);
 assert.match(calls.find(c=>c.label==='check').prompt,/distinguish the competing explanations before repair/);
 assert.deepEqual(result.commands,[]);
});
test('source cause confirmed only with independent evidence and readonly stages',async()=>{const {result,calls}=await run();assert.equal(result.status,'completed');assert.equal(result.cause_status,'confirmed');assert.equal(result.hypotheses[0].status,'confirmed');assert.deepEqual(result.changedPaths,[]);assert.deepEqual(result.commands,[]);assert.ok(result.next_actions.length);for(const c of calls){const marker=JSON.parse(c.prompt.split('\n')[0].slice('__AUTO_RECIPE_ROLE__'.length));assert.equal(marker.readOnly,true);assert.equal(marker.token,'token');assert.ok(marker.timeoutMs>0);assert.equal(marker.role,c.label==='check'?'investigation-checker':c.label==='scope'?'investigation-scope':'investigator');assert.deepEqual(c.violations,[]);}});
for(const label of ['scope','gather','check'])for(const bad of [null,{},()=>{throw Error('failed');}])test('missing/malformed/exception '+label+' never confirms',async()=>{const {result}=await run({[label]:bad});assert.equal(result.status,'completed_with_failures');assert.equal(result.cause_status,'inconclusive');assert.ok(result.hypotheses.every(h=>h.status!=='confirmed'));});
for(const resolutions of [[],[resolution(),resolution()],[resolution('unknown')],[{...resolution(),evidence:''}],[{...resolution(),confidence:2}]])test('exact checker hypothesis accounting '+JSON.stringify(resolutions),async()=>{const {result}=await run({check:{...check(),resolutions}});assert.equal(result.status,'completed_with_failures');assert.equal(result.hypotheses[0].status,'inconclusive');});
for(const status of ['confirmed','rejected'])test('uncovered resolution cannot discard or confirm '+status,async()=>{const {result}=await run({check:{...check(),coverage:[],resolutions:[resolution('H1',status)]}});assert.equal(result.status,'completed_with_failures');assert.equal(result.hypotheses[0].status,'inconclusive');});
test('rejection remains explicit with source evidence',async()=>{const {result}=await run({check:{...check(),resolutions:[resolution('H1','rejected')]}});assert.equal(result.cause_status,'rejected');assert.equal(result.status,'completed');assert.equal(result.hypotheses[0].sources.length,1);});
test('unknown cause remains inconclusive',async()=>{const {result}=await run({check:{...check(),resolutions:[resolution('H1','inconclusive')]}});assert.equal(result.status,'completed_with_failures');assert.equal(result.cause_status,'inconclusive');});
test('no hypothesis is not proof of rejected cause',async()=>{const {result}=await run({gather:{...gather(),hypotheses:[]},check:{...check(),resolutions:[]}});assert.equal(result.cause_status,'inconclusive');assert.equal(result.status,'completed_with_failures');});
test('distinct hypotheses with same local id survive with stable global ids',async()=>{const {result}=await run({gather:{...gather(),hypotheses:[hypothesis(),{...hypothesis(),cause:'Different cause'}]},check:{...check(),resolutions:[resolution('H1'),resolution('H2','rejected')]}});assert.equal(result.hypotheses.length,2);assert.deepEqual(result.hypotheses.map(h=>h.id),['H1','H2']);});
for(const file of ['../outside','/absolute','src/*.js','unknown.js'])test('bad hypothesis file '+file,async()=>{const {result}=await run({gather:{...gather(),hypotheses:[{...hypothesis(),file}]}});assert.equal(result.status,'completed_with_failures');assert.equal(result.cause_status,'inconclusive');});
for(const label of ['scope','gather','check'])test('partial '+label+' cannot establish overall cause',async()=>{const defaults={scope:scope(),gather:gather(),check:check()};const {result}=await run({[label]:{...defaults[label],complete:false}});assert.equal(result.status,'completed_with_failures');assert.equal(result.cause_status,'inconclusive');});
test('mixed confirmed and inconclusive statuses are order independent',async()=>{const hypotheses=[hypothesis(),{...hypothesis(),cause:'Second',line:4}];for(const statuses of [['confirmed','inconclusive'],['inconclusive','confirmed']]){const {result}=await run({gather:{...gather(),hypotheses},check:{...check(),resolutions:statuses.map((s,i)=>resolution('H'+(i+1),s))}});assert.deepEqual(result.hypotheses.map(h=>h.status),statuses);assert.equal(result.cause_status,'inconclusive');}});
for(const files of [[],Array.from({length:41},(_,i)=>`file${i}.js`),['src/a.js','src/a.js'],['../a']])test('scope bounded concrete unique '+JSON.stringify(files),async()=>{const {result,calls}=await run({scope:{...scope(),files}});assert.equal(result.status,'completed_with_failures');assert.equal(calls.length,1);});
for(const args of [{task:''},{repo:'relative'},{repo:'/repo/../else'}])test('required canonical input '+JSON.stringify(args),async()=>{await assert.rejects(run({},args));});
