import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFile,mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import path from 'node:path';import os from 'node:os';
import {apply} from '../lib/recipes.mjs';
import {approveRecipe} from '../lib/recipe-integrity.mjs';
import {RECIPES_DIR} from '../lib/dsh-paths.mjs';
import {createPtcFixture} from './helpers/ptc-runtime.mjs';
const command=(command='node --test',exitCode=0)=>({command,exitCode,evidence:'observed defect assertion output',passed:exitCode===0});
const examples={
 'feature-pipeline':{setup:{stack:'JS',testCommands:['node --test'],lintCommands:[],conventions:[]},analysis:{scope:{files:['src.js'],symbols:[],dependents:[],tests:[]},currentState:'source exists',gaps:['scoped change'],outcome:'proceed',outcomeReason:'scoped task',decisions:[]},'quick-spec':{acceptance:['Requested behavior'],verifyCommands:['node --test'],plan:'Update src.js and verify'},implement:{changedPaths:['src.js'],commands:[command()],notes:'changed',decisions:[]},'review-1':{verdict:'APPROVED',summary:'verified',findings:[]},'review-2':{verdict:'APPROVED',summary:'verified',findings:[]},validate:{results:[{criterion:'Requested behavior',status:'passed',evidence:'observed test'}],summary:'verified'}},
 'qa-verify':{analysis:{files:['src.js'],criteria:[{id:'criterion-one',criterion:'Expected source contract',basis:'explicit task',files:['src.js'],proof:'source',commands:[],limitedBy:[]}],commands:[],complete:true,limitations:[]},verify:{results:[{id:'criterion-one',status:'passed',proof:'source',evidence:'inspected source',files:['src.js'],commands:[]}],commands:[],coverage:['src.js'],complete:true,limitations:[]},check:{results:[{id:'criterion-one',status:'passed',proof:'source',evidence:'independent source',files:['src.js'],commands:[],reason:'explicit criterion met'}],commands:[],coverage:['src.js'],complete:true,limitations:[]}},
 'refactor':{setup:{verifyCommands:['node --test'],evidence:'package.json test'},analysis:{files:['src.js','test.js'],tests:['test.js'],invariants:['Behavior unchanged'],acceptance:['Structure improved'],clear:true,questions:[],evidence:'source'},baseline:{commands:[command()],evidence:'untouched passing tests'},implement:{changedPaths:['src.js'],commands:[command()],behaviorChanged:false,testsWeakened:false,notes:'restructure'},'review-1':{verdict:'APPROVED',findings:[],evidence:'diff checked'},'review-2':{verdict:'APPROVED',findings:[],evidence:'diff checked'},validate:{invariants:[{criterion:'Behavior unchanged',passed:true,evidence:'tests'}],acceptance:[{criterion:'Structure improved',passed:true,evidence:'diff'}],commands:[command()],behaviorChanged:false,testsWeakened:false,evidence:'fresh tests'}},
 'plan-to-packages':{evidence:{goals:[{id:'goal-one',description:'Deliver scoped change'}],files:['package.json','src.js'],commands:[{command:'node --test',file:'package.json',evidence:'test script'}],complete:true,questions:[]},packages:{packages:[{id:'package-one',title:'Scoped change',description:'Implement goal',writePaths:['src.js'],acceptance:['Goal fulfilled'],verifyCommands:['node --test'],dependencies:[],goalIds:['goal-one'],recipe:'feature-pipeline',serializationReason:'',evidence:'src.js inspected'}],complete:true,questions:[]},check:{packages:[{id:'package-one',passed:true,evidence:'scope verified'}],goals:[{id:'goal-one',passed:true,evidence:'goal covered'}],complete:true,questions:[]}},
 'investigate':{scope:{files:['src.js'],summary:'source scope',complete:true,limitations:[]},gather:{hypotheses:[{id:'one',cause:'Incorrect boundary',file:'src.js',line:1,evidence:'source evidence',confidence:0.8}],coverage:['src.js'],complete:true,limitations:[]},check:{resolutions:[{id:'H1',status:'confirmed',reason:'source verified',evidence:'src.js:1 evidence',confidence:0.8}],coverage:['src.js'],complete:true,limitations:[],next_actions:['Reproduce defect before repair']}},
 'code-audit':{scope:{files:['src.js'],summary:'Scoped source',complete:true,limitations:[]},'scan-security':{findings:[],coverage:['src.js'],complete:true,limitations:[]},'scan-correctness':{findings:[],coverage:['src.js'],complete:true,limitations:[]},verify:{resolutions:[],coverage:['src.js'],complete:true,limitations:[]}},
 'bug-fix':{setup:{stack:'JS',verifyCommands:['node --test'],conventions:[]},analysis:{scope:{files:['src.js','test.js'],tests:['test.js'],symbols:[],dependents:[]},outcome:'reproducible',reason:'Source confirms bug',currentState:'wrong',expectedBehavior:'right',acceptance:['Regression fixed'],decisions:[]},implement:{changedPaths:['src.js','test.js'],commands:[command()],regression:{red:{...command('node --test test.js',1),failureKind:'assertion',testExecuted:true},green:command('node --test test.js'),beforeProduction:true},notes:'fixed',decisions:[]},'review-1':{verdict:'APPROVED',summary:'verified',findings:[]},'review-2':{verdict:'APPROVED',summary:'verified',findings:[]},validate:{results:[{criterion:'Regression fixed',status:'passed',evidence:'actual tests'}],commands:[command(),command('node --test test.js')],summary:'verified'}}
};
for(const name of ['feature-pipeline','code-audit','bug-fix','investigate','plan-to-packages','refactor','qa-verify'])test(name+' actual saved body crosses run_recipe and real PTC engine',{timeout:60000},async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'new-recipe-worker-'));let tool,runtime;const listeners=new Map(),requests=[];
 try{const dir=path.join(root,'recipes'),base=path.join(dir,name);await mkdir(base,{recursive:true});
 for(const file of ['meta.json','script.js'])await writeFile(path.join(base,file),await readFile(path.join(RECIPES_DIR,name,file),'utf8'));
 await approveRecipe(base,{approvedBy:'offline-fixture-not-production'});
 const provider={capabilities:{agentOptions:true,outputSchema:true,toolFilter:true},inheritsParentContext:false,async start(req){requests.push(req);const markerLabel=req.descriptor?.label; const text=req.prompt.map(p=>p.text??'').join('\n');
 // Labels are on the one-shot descriptor supplied by the actual engine/registry.
 const label=markerLabel??req.descriptor?.workflow?.label??(name==='feature-pipeline'?['setup','analysis','quick-spec','implement #1','review-1 #1','review-2 #1','validate'][requests.length-1]:name==='qa-verify'?['analysis','verify','check'][requests.length-1]:name==='refactor'?['setup','analysis','baseline','implement #1','review-1 #1','review-2 #1','validate'][requests.length-1]:name==='plan-to-packages'?['evidence','packages','check'][requests.length-1]:name==='investigate'?['scope','gather','check'][requests.length-1]:name==='code-audit'?['scope','scan-security','scan-correctness','verify'][requests.length-1]:['setup','analysis','implement #1','review-1 #1','review-2 #1','validate'][requests.length-1]);
 const value=examples[name][label.replace(/ #\d+$/,'')];assert.ok(value,'known fixture label '+label);
 return{id:'fixture-'+requests.length,result:Promise.resolve({stopReason:'completed',output:[],structured:structuredClone(value)}),async dispose(){}};
 }};
 const providers=new Map([['spawn',provider]]);const ctx={logger:{warn(){}},tools:{register:t=>tool=t},on(n,fn){const s=listeners.get(n)??new Set();s.add(fn);listeners.set(n,s);return()=>s.delete(fn);},emit(n,...a){for(const fn of listeners.get(n)??[])fn(...a);},events:{dispatch(_k,[n,...a]){return[...(listeners.get(n)??[])].map(fn=>()=>fn(...a));}},subagents:{getProvider:n=>providers.get(n),registerProvider(p){providers.set(p.name,p);return()=>providers.delete(p.name);},start(n,r){return providers.get(n).start(r);}},subagentModelSelection:{current:()=>({enabled:true,allowedModels:['A','B','C'].map(model=>({provider:'fixture',model})),modelTiers:['A','B','C'].map(model=>({provider:'fixture',model,tier:'strong'}))})},llm:{listProviders:()=>[{id:'fixture'}],resolveCallConfig:async c=>c}};
 runtime=await createPtcFixture({cwd:root,provider,events:ctx});ctx.subagents=runtime.subagents;ctx.workflowEngine=runtime.engine;
 apply(ctx,{recipesDir:dir,runsDir:path.join(root,'runs'),setupCacheDir:path.join(root,'cache')});
 const parent=runtime.createParent();
 const result=await tool.execute({recipe:name,repo:root,task:'offline worker fixture'},{agent:parent,signal:new AbortController().signal});
 assert.equal(result.result.status,'completed');assert.ok(requests.length>=(['investigate','plan-to-packages','qa-verify'].includes(name)?3:4));
 if(['code-audit','investigate','plan-to-packages'].includes(name))for(const req of requests)assert.deepEqual(req.toolFilter,{allow:['read','read_image','glob','grep']});
 assert.ok(requests.every(req=>req.agentOptions.provider==='fixture'));
 assert.deepEqual(runtime.subagents.list(), ['spawn'], 'the private route provider is removed after settlement');
 }finally{try{await runtime?.dispose();}finally{await rm(root,{recursive:true,force:true});}}
});
