import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import path from 'node:path';import {RECIPES_DIR,runtimeModuleUrl} from '../lib/dsh-paths.mjs';const {assertObjectJsonSchema,validateJsonSchemaValue}=await import(runtimeModuleUrl('@deepseek-ai/dsh-tools'));const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
const evidence=()=>({goals:[{id:'g1',description:'Implement feature'}],files:['a.js','b.js','package.json'],commands:[{command:'npm test',file:'package.json',evidence:'scripts.test'}],complete:true,questions:[]});
const pkg=(id='p1',paths=['a.js'],dependencies=[])=>({id,title:id,description:'Cohesive feature',writePaths:paths,acceptance:['Works'],verifyCommands:['npm test'],dependencies,goalIds:['g1'],recipe:'feature-pipeline',serializationReason:dependencies.length?'Dependent shared work':'',evidence:'a.js source'});
const draft=()=>({packages:[pkg()],complete:true,questions:[]});const check=()=>({packages:[{id:'p1',passed:true,evidence:'read source'}],goals:[{id:'g1',passed:true,evidence:'covered'}],complete:true,questions:[]});
async function run(overrides={},args={}){const source=await readFile(path.join(RECIPES_DIR,'plan-to-packages','script.js'),'utf8');const fn=new AsyncFunction('agent','parallel','phase','log','args',source);const calls=[];const defs={evidence:evidence(),packages:draft(),check:check()};const agent=async(prompt,opts)=>{assertObjectJsonSchema(opts.schema);assert.deepEqual(Object.keys(opts).sort(),['label','phase','schema']);calls.push({prompt,...opts});const v=Object.hasOwn(overrides,opts.label)?overrides[opts.label]:defs[opts.label];if(v!==null)assert.deepEqual(validateJsonSchemaValue(opts.schema,v),[]);return v;};return {result:await fn(agent,thunks=>Promise.all(thunks.map(t=>t())),()=>{},()=>{},{task:'Plan feature',repo:'/repo',routingToken:'token',...args}),calls};}
test('actual plan completes exact package/goal verification and readonly markers',async()=>{const {result,calls}=await run();assert.equal(result.status,'completed');assert.deepEqual(result.topologicalOrder,['p1']);assert.deepEqual(result.parallelFronts,[['p1']]);for(const c of calls)assert.equal(JSON.parse(c.prompt.split('\n')[0].slice('__AUTO_RECIPE_ROLE__'.length)).readOnly,true);assert.deepEqual(result.changedPaths,[]);});
for(const [label,value] of [['evidence',{...evidence(),complete:false,questions:['Which feature?']}],['packages',{...draft(),complete:false}],['check',{...check(),complete:false}]])test('partial '+label+' cannot certify plan',async()=>{assert.notEqual((await run({[label]:value})).result.status,'completed');});
for(const packages of [[pkg('p1', ['../escape'])],[pkg('p1',['dir/'])],[pkg('p1',['*.js'])],[pkg(),pkg()],[pkg('p1',['a.js'],['missing'])],[pkg('p1',['a.js'],['p1'])],[pkg('p1',['a.js'],['p2']),pkg('p2',['b.js'],['p1'])],[pkg('p1'),pkg('p2',['a.js'])],[{...pkg(),goalIds:[]}],[{...pkg(),recipe:'invented'}],[{...pkg(),verifyCommands:['invented command']}],[{...pkg(),goalIds:['missing']}],Array.from({length:21},(_,i)=>pkg('p'+i))])test('unsafe DAG rejected '+JSON.stringify(packages).slice(0,70),async()=>{const {result}=await run({packages:{...draft(),packages}});assert.equal(result.status,'completed_with_failures');assert.deepEqual(result.topologicalOrder,[]);});
test('dependent overlap serialized; incomparable independent packages share ready frontier',async()=>{const packages=[pkg('p1'),pkg('p2',['a.js'],['p1']),pkg('p3',['b.js'])];const {result}=await run({packages:{...draft(),packages},check:{...check(),packages:packages.map(p=>({id:p.id,passed:true,evidence:'read'}))}});assert.equal(result.status,'completed');assert.deepEqual(result.parallelFronts,[['p1','p3'],['p2']]);});
for(const packages of [[],[{id:'p1',passed:true,evidence:'read'},{id:'p1',passed:true,evidence:'read'}],[{id:'other',passed:true,evidence:'read'}]])test('checker exact package set '+JSON.stringify(packages),async()=>assert.notEqual((await run({check:{...check(),packages}})).result.status,'completed'));
for(const goals of [[],[{id:'g1',passed:false,evidence:'missing'}],[{id:'other',passed:true,evidence:'x'}]])test('checker exact goal set '+JSON.stringify(goals),async()=>assert.notEqual((await run({check:{...check(),goals}})).result.status,'completed'));
for(const label of ['evidence','packages','check'])test('null '+label+' stays incomplete',async()=>assert.notEqual((await run({[label]:null})).result.status,'completed'));
for(const packages of [[pkg('p1',['src']),pkg('p2',['src/a.js'])],[pkg('p1',['src','src/a.js'])]])test('ancestor scope not concrete disjoint files '+JSON.stringify(packages),async()=>assert.equal((await run({packages:{...draft(),packages},check:{...check(),packages:packages.map(p=>({id:p.id,passed:true,evidence:'checked'}))}})).result.status,'completed_with_failures'));
for(const args of [{task:''},{repo:'relative'}])test('required input '+JSON.stringify(args),async()=>assert.rejects(run({},args)));

for(const recipe of ['investigate','code-audit','qa-verify','refactor'])test('package selector supports '+recipe+' with exact goal/check accounting',async()=>{const p={...pkg(),recipe,writePaths:['refactor'].includes(recipe)?['a.js']:[],verifyCommands:['investigate','code-audit'].includes(recipe)?[]:['npm test']};const {result,calls}=await run({packages:{...draft(),packages:[p]}});assert.equal(result.status,'completed');assert.deepEqual(result.topologicalOrder,['p1']);assert.match(calls.find(c=>c.label==='check').prompt,/cannot certify runtime behavior/);});
for(const recipe of ['feature-pipeline','bug-fix','refactor'])test('editing recipe '+recipe+' still requires change scope and verification',async()=>{for(const fields of [{writePaths:[]},{verifyCommands:[]}])assert.equal((await run({packages:{...draft(),packages:[{...pkg(),recipe,...fields}]}})).result.status,'completed_with_failures');});
test('source-only QA acceptance does not invent runtime verification commands',async()=>{const {result,calls}=await run({packages:{...draft(),packages:[{...pkg(),recipe:'qa-verify',writePaths:[],verifyCommands:[]}]}});assert.equal(result.status,'completed');assert.match(calls.find(c=>c.label==='packages').prompt,/QA runtime criteria require evidenced commands/);assert.match(calls.find(c=>c.label==='packages').prompt,/reader\/writer independence/);});
test('recursive package planner is not a goal execution recipe',async()=>{const {result}=await run({packages:{...draft(),packages:[{...pkg(),recipe:'plan-to-packages'}]}});assert.equal(result.status,'completed_with_failures');assert.deepEqual(result.topologicalOrder,[]);});
