import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import path from 'node:path';import {RECIPES_DIR,runtimeModuleUrl} from '../lib/dsh-paths.mjs';
const {assertObjectJsonSchema,validateJsonSchemaValue}=await import(runtimeModuleUrl('@deepseek-ai/dsh-tools'));
const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor,dir=path.join(RECIPES_DIR,'qa-verify');
const criterion=()=>({id:'C1',criterion:'Input rejected',basis:'task requirement and requirements.md:2',files:['src.js'],proof:'runtime',commands:['node --test test.js']});
const analysis=()=>({files:['src.js','test.js','requirements.md'],criteria:[criterion()],commands:[{command:'node --test test.js',definition:'package.json test script',safe:true}],complete:true,limitations:[]});
const cmd=()=>({command:'node --test test.js',status:'passed',exitCode:0,evidence:'1 assertion passed'});
const row=()=>({id:'C1',status:'passed',proof:'runtime',evidence:'Input-rejection regression assertion passed',files:['src.js'],commands:['node --test test.js']});
const verification=()=>({results:[row()],commands:[cmd()],coverage:['src.js','test.js','requirements.md'],complete:true,limitations:[]});
const checked=()=>({results:[{...row(),reason:'Independent assertion rerun confirms requirement'}],commands:[cmd()],coverage:['src.js','test.js','requirements.md'],complete:true,limitations:[]});
async function run(overrides={},args={}){const fn=new AsyncFunction('agent','parallel','phase','log','args',await readFile(path.join(dir,'script.js'),'utf8'));const calls=[],defaults={analysis:analysis(),verify:verification(),check:checked()};const agent=async(prompt,opts)=>{assert.deepEqual(Object.keys(opts).sort(),['label','phase','schema']);assertObjectJsonSchema(opts.schema);calls.push({prompt,...opts});let v=Object.hasOwn(overrides,opts.label)?overrides[opts.label]:defaults[opts.label];if(typeof v==='function')v=await v(prompt);if(v!=null)calls.at(-1).violations=validateJsonSchemaValue(opts.schema,v);return structuredClone(v);};return{result:await fn(agent,h=>Promise.all(h.map(f=>f())),()=>{},()=>{},{task:'Verify input rejected',repo:'/repo',routingToken:'token',...args}),calls};}
test('saved QA custom strong roles and3phases',async()=>{const m=JSON.parse(await readFile(path.join(dir,'meta.json'),'utf8'));assert.equal(m.name,'qa-verify');assert.equal(m.roles['qa-verifier'].tier,'strong');assert.equal(m.roles['qa-checker'].tier,'strong');assert.equal(m.phases.length,3);});
test('exact criteria independent runtime evidence completed without repair',async()=>{const {result,calls}=await run();assert.equal(result.status,'completed');assert.equal(result.results[0].status,'passed');assert.deepEqual(result.changedPaths,[]);assert.equal(result.commands.length,2);for(const c of calls){assert.deepEqual(c.violations,[]);const m=JSON.parse(c.prompt.split('\n')[0].slice('__AUTO_RECIPE_ROLE__'.length));assert.equal(m.readOnly,c.label==='analysis');assert.ok(m.timeoutMs>0);assert.equal(m.role,c.label==='check'?'qa-checker':'qa-verifier');}});
test('missing acceptance ends without inventing success or executing commands',async()=>{const {result,calls}=await run({analysis:{...analysis(),criteria:[]}});assert.equal(result.status,'ended');assert.deepEqual(result.results,[]);assert.equal(calls.length,1);});
for(const label of ['analysis','verify','check'])for(const bad of [null,{},()=>{throw Error('child failed');}])test('no PASS from bad '+label,async()=>{const {result}=await run({[label]:bad});assert.equal(result.status,'completed_with_failures');assert.ok(result.results.every(r=>r.status!=='passed'));});
for(const label of ['verify','check'])for(const results of [[],[row(),row()],[{...row(),id:'unknown'}],[{...row(),evidence:''}]])test('exact criteria accounting '+label+JSON.stringify(results),async()=>{const shaped=label==='check'?results.map(r=>({...r,reason:'checked'})):results;const {result}=await run({[label]:{...(label==='check'?checked():verification()),results:shaped}});assert.equal(result.status,'completed_with_failures');assert.ok(result.results.every(r=>r.status!=='passed'));});
for(const label of ['verify','check'])test('uncovered criterion fails closed '+label,async()=>{const {result}=await run({[label]:{...(label==='check'?checked():verification()),coverage:['test.js']}});assert.equal(result.status,'completed_with_failures');assert.equal(result.results[0].status,'blocked');});
for(const label of ['verify','check'])for(const commands of [[],[{...cmd(),command:'unknown'}],[cmd(),cmd()],[{...cmd(),evidence:''}],[{...cmd(),exitCode:1}]])test('runtime command evidence required '+label+JSON.stringify(commands),async()=>{const {result}=await run({[label]:{...(label==='check'?checked():verification()),commands}});assert.equal(result.status,'completed_with_failures');assert.ok(result.results.every(r=>r.status!=='passed'));});
test('source-only evidence cannot satisfy runtime requirement',async()=>{const {result}=await run({check:{...checked(),results:[{...row(),proof:'source',reason:'read only'}]}});assert.equal(result.status,'completed_with_failures');assert.equal(result.results[0].status,'blocked');});
test('source requirement may complete but explicitly reports no runtime proof',async()=>{const c={...criterion(),proof:'source',commands:[]};const {result}=await run({analysis:{...analysis(),criteria:[c],commands:[]},verify:{...verification(),results:[{...row(),proof:'source',commands:[]}],commands:[]},check:{...checked(),results:[{...row(),proof:'source',commands:[],reason:'source checked'}],commands:[]}});assert.equal(result.status,'completed');assert.equal(result.results[0].proof,'source');assert.ok(result.limitations.some(s=>s.includes('Source')));});
test('checker failure overrides author PASS',async()=>{const {result}=await run({check:{...checked(),results:[{...row(),status:'failed',reason:'actual regression broken'}],commands:[{...cmd(),status:'failed',exitCode:1}]}});assert.equal(result.status,'completed_with_failures');assert.equal(result.results[0].status,'failed');});
for(const label of ['analysis','verify','check'])test('partial stage cannot certify QA '+label,async()=>{const defaults={analysis:analysis(),verify:verification(),check:checked()};const {result}=await run({[label]:{...defaults[label],complete:false}});assert.equal(result.status,'completed_with_failures');});
for(const criteria of [[criterion(),criterion()],[{...criterion(),basis:''}],[{...criterion(),files:['../outside']}],[{...criterion(),commands:[]}],[{...criterion(),commands:['other']}]])test('invalid criterion contract aborts verification '+JSON.stringify(criteria),async()=>{const {result,calls}=await run({analysis:{...analysis(),criteria}});assert.equal(result.status,'completed_with_failures');assert.equal(calls.length,1);});
for(const label of ['verify','check'])for(const status of ['failed','blocked'])test('additional authorized command '+status+' prevents completion '+label,async()=>{const extra={command:'node lint.js',status,exitCode:status==='failed'?1:0,evidence:'lint failed or blocked'};const defaults=label==='check'?checked():verification();const {result}=await run({analysis:{...analysis(),commands:[...analysis().commands,{command:'node lint.js',definition:'manifest lint check',safe:true}]},[label]:{...defaults,commands:[...defaults.commands,extra]}});assert.equal(result.status,'completed_with_failures');assert.ok(result.commands.some(c=>c.command===extra.command&&c.status===status));});
test('same criterion text with different ids is not unique acceptance',async()=>{const {result,calls}=await run({analysis:{...analysis(),criteria:[criterion(),{...criterion(),id:'C2'}]}});assert.equal(result.status,'completed_with_failures');assert.equal(calls.length,1);});
test('unsafe command prevents execution',async()=>{const {result,calls}=await run({analysis:{...analysis(),commands:[{...analysis().commands[0],safe:false}]}});assert.equal(result.status,'completed_with_failures');assert.equal(calls.length,1);});
for(const args of [{task:''},{repo:'relative'},{repo:'/repo/../else'}])test('input rejection '+JSON.stringify(args),async()=>await assert.rejects(run({},args)));
for(const verifierStatus of ['failed','blocked'])test(`checker PASS cannot replace verifier ${verifierStatus} evidence`,async()=>{
 const verifierEvidence=`Observed author ${verifierStatus}`,checkerEvidence='Independent checker passed';
 const verify={...verification(),results:[{...row(),status:verifierStatus,evidence:verifierEvidence}],commands:[{...cmd(),status:verifierStatus,exitCode:verifierStatus==='failed'?1:0,evidence:verifierEvidence}]};
 const check={...checked(),results:[{...checked().results[0],evidence:checkerEvidence}]};
 const {result}=await run({verify,check});const r=result.results[0];assert.equal(result.status,'completed_with_failures');assert.equal(r.status,verifierStatus);assert.equal(r.evidence,verifierEvidence);assert.equal(r.verifierEvidence,verifierEvidence);assert.equal(r.checkerEvidence,checkerEvidence);
});
// User journey: checker outages must not erase observed failure/blocker evidence or certify author-only PASS.
for(const verifierStatus of ['failed','blocked','passed'])for(const [failure,checker] of [['missing',null],['malformed',{}],['exception',()=>{throw Error('checker unavailable');}]])test(`verifier ${verifierStatus} survives ${failure} checker without author-only PASS`,async()=>{
 const evidence=`Observed verifier ${verifierStatus} evidence`;
 const verify={...verification(),results:[{...row(),status:verifierStatus,evidence}],commands:[{...cmd(),status:verifierStatus,exitCode:verifierStatus==='failed'?1:0,evidence}]};
 const {result,calls}=await run({verify,check:checker});
 assert.equal(result.status,'completed_with_failures');assert.deepEqual(calls.find(c=>c.label==='verify').violations,[]);
 const r=result.results[0];assert.equal(r.status,verifierStatus==='passed'?'blocked':verifierStatus);
 assert.equal(r.verifierStatus,verifierStatus);assert.equal(r.verifierEvidence,evidence);assert.equal(r.checkerStatus,'blocked');
 assert.equal(r.criterion,criterion().criterion);assert.equal(r.basis,criterion().basis);
 if(verifierStatus!=='passed'){assert.equal(r.evidence,evidence);assert.deepEqual(r.files,row().files);assert.deepEqual(r.commands,row().commands);}
});
