import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import path from 'node:path';import {RECIPES_DIR,runtimeModuleUrl} from '../lib/dsh-paths.mjs';const {assertObjectJsonSchema,validateJsonSchemaValue}=await import(runtimeModuleUrl('@deepseek-ai/dsh-tools'));const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
const cmd=(exitCode=0)=>({command:'npm test',exitCode,passed:exitCode===0,evidence:'executed output'});const analysis=()=>({verifyCommands:['npm test'],files:['src.js','test.js'],tests:['test.js'],invariants:['Same API','Same output'],acceptance:['Structure improved'],clear:true,questions:[],evidence:'actual source'});const impl=()=>({changedPaths:['src.js'],commands:[cmd()],behaviorChanged:false,testsWeakened:false,notes:'extract helper'});const review=()=>({verdict:'APPROVED',findings:[],evidence:'actual diff'});const valid=()=>({invariants:['Same API','Same output'].map(criterion=>({criterion,passed:true,evidence:'verified'})),acceptance:[{criterion:'Structure improved',passed:true,evidence:'verified'}],commands:[cmd()],behaviorChanged:false,testsWeakened:false,evidence:'fresh'});
async function run(overrides={},args={}){const source=await readFile(path.join(RECIPES_DIR,'refactor','script.js'),'utf8');const fn=new AsyncFunction('agent','parallel','phase','log','args',source);const calls=[],count={},logs=[];const defs={analysis:analysis(),baseline:{commands:[cmd()],evidence:'untouched green baseline'},implement:impl(),'review-1':review(),'review-2':review(),validate:valid()};const agent=async(prompt,opts)=>{assertObjectJsonSchema(opts.schema);assert.deepEqual(Object.keys(opts).sort(),['label','phase','schema']);calls.push({prompt,...opts});const key=opts.label.replace(/ #\d+$/,'');count[key]=(count[key]||0)+1;let v=Object.hasOwn(overrides,key)?overrides[key]:defs[key];v=typeof v==='function'?v(count[key],prompt):v;if(v!==null)assert.deepEqual(validateJsonSchemaValue(opts.schema,v),[]);return v;};return {result:await fn(agent,thunks=>Promise.all(thunks.map(t=>Promise.resolve().then(t).catch(()=>null))),()=>{},message=>logs.push(message),{task:'Extract helper',repo:'/repo',routingToken:'token',...args}),calls,logs};}
import {RunTracker} from '../lib/run-tracker.mjs';
import {initialState,reduce,nodesOf,nodeState} from '../lib/card-model.mjs';
// Replay actual recipe log messages, rather than synthetic signals, onto actual reviewer nodes.
for(const rejection of ['explicit','high','missing'])test(`actual ${rejection} reviewer verdicts and findings survive tracker/card replay across repairs`,async()=>{
 const finding={id:'api-drift',severity:rejection==='explicit'?'medium':'high',problem:'API drift',requiredFix:'Restore API'};
 const {result,calls,logs}=await run({'review-1':n=>n>1?review():rejection==='missing'?null:{...review(),verdict:rejection==='explicit'?'NEEDS_REVISION':'APPROVED',findings:[finding]}});
 assert.equal(result.status,'completed');
 const events=[],info={id:'engine'},tracker=new RunTracker({session:{append(type,data){events.push({type,data});}}},'card',{});tracker.bind(info.id);
 for(const [i,c] of calls.entries()){tracker.onAgentStart(info,{seq:i+1,label:c.label,phase:c.phase,childId:`child-${i}`});tracker.onAgentEnd(info,{seq:i+1,outcome:'completed'});}
 for(const message of logs)tracker.onLog(info,message);
 const state=events.reduce((s,e)=>reduce(s,e.type,e.data),initialState({runId:'card',recipe:'refactor',task:'Extract helper',repo:'/repo',routes:{}}));
 const nodes=nodesOf(state);assert.equal(nodes.history.r1.length,2);assert.equal(nodes.history.r2.length,2);
 const first=nodes.history.r1[0];assert.equal(first.verdict,'no');assert.equal(nodeState(first),'failed');
 assert.ok(first.findings.some(f=>rejection==='missing'?/Missing independent review/.test(f.problem):f.problem===finding.problem));
 assert.equal(nodes.history.r2[0].verdict,'ok');assert.equal(nodes.latest.r1.verdict,'ok');assert.equal(nodes.latest.r2.verdict,'ok');
 const annotations=events.filter(e=>e.data.annotate&&e.data.verdict);assert.equal(annotations.filter(e=>e.data.label?.startsWith('review-')).length,4);assert.ok(annotations.every(e=>e.data.seq!==null));
});
test('green untouched baseline precedes implementation; exact final invariants complete',async()=>{const {result,calls}=await run();assert.equal(result.status,'completed');assert.deepEqual(result.changedPaths,['src.js']);assert.ok(calls.findIndex(c=>c.label==='baseline')<calls.findIndex(c=>c.label.startsWith('implement')));for(const c of calls){const m=JSON.parse(c.prompt.split('\n')[0].slice('__AUTO_RECIPE_ROLE__'.length));assert.equal(m.readOnly,c.label==='analysis');}});
for(const key of ['analysis','baseline','implement','validate'])test('missing '+key+' fails closed',async()=>assert.notEqual((await run({[key]:null})).result.status,'completed'));
test('failing baseline aborts without implementation',async()=>{const {result,calls}=await run({baseline:{commands:[cmd(1)],evidence:'preexisting failure'}});assert.equal(result.status,'aborted');assert.ok(!calls.some(c=>c.label.startsWith('implement')));});
test('unclear invariants end without edits or forged resume',async()=>{const {result,calls}=await run({analysis:{...analysis(),clear:false,questions:['API behavior?']}});assert.equal(result.status,'ended');assert.equal(calls.length,1);assert.ok(!result.resume);});
for(const v of [{...impl(),behaviorChanged:true},{...impl(),testsWeakened:true},{...impl(),commands:[]},{...impl(),commands:[cmd(1)]},{...impl(),changedPaths:['../outside']},{...impl(),changedPaths:['unknown.js']}])test('unsafe implementation aborts '+JSON.stringify(v),async()=>assert.equal((await run({implement:v})).result.status,'aborted'));
for(const r of [null,{...review(),verdict:'NEEDS_REVISION'},{...review(),findings:[{id:'x',severity:'high',problem:'Changed behavior',requiredFix:'restore'}]}])test('review fails closed '+JSON.stringify(r),async()=>{const {result,calls}=await run({'review-2':r});assert.equal(result.status,'aborted');assert.equal(result.reviewTrail.length,3);assert.ok(!calls.some(c=>c.label==='validate'));});
test('repair feedback and baseline retained while paths accumulate',async()=>{const f={id:'x',severity:'medium',problem:'API drift',requiredFix:'restore API'};const {result,calls}=await run({implement:n=>({...impl(),changedPaths:n===1?['test.js']:['src.js']}),'review-1':n=>n===1?{...review(),verdict:'NEEDS_REVISION',findings:[f]}:review()});assert.equal(result.status,'completed');assert.deepEqual(result.changedPaths,['test.js','src.js']);assert.equal(calls.filter(c=>c.label==='baseline').length,1);assert.match(calls.find(c=>c.label==='implement #2').prompt,/restore API/);});
for(const invariants of [[],[valid().invariants[0]],[...valid().invariants,valid().invariants[0]],[...valid().invariants,{criterion:'Other',passed:true,evidence:'x'}]])test('invariant validation exact '+JSON.stringify(invariants),async()=>assert.equal((await run({validate:{...valid(),invariants}})).result.status,'completed_with_failures'));
for(const v of [{...valid(),testsWeakened:true},{...valid(),behaviorChanged:true},{...valid(),commands:[cmd(1)]},{...valid(),acceptance:[]}])test('final evidence cannot certify drift '+JSON.stringify(v),async()=>assert.equal((await run({validate:v})).result.status,'completed_with_failures'));

test('one read-only analysis sources commands and invariants before untouched baseline',async()=>{const {calls}=await run();assert.equal(calls.filter(c=>c.label==='analysis').length,1);assert.ok(!calls.some(c=>c.label==='setup'));assert.deepEqual(calls.slice(0,2).map(c=>c.label),['analysis','baseline']);assert.match(calls[0].prompt,/No commands or edits/);assert.match(calls[1].prompt,/npm test/);assert.match(calls[1].prompt,/Same API/);});
for(const verifyCommands of [[],[''],['npm test','npm test']])test('missing or ambiguous sourced commands prevent baseline '+JSON.stringify(verifyCommands),async()=>{const {result,calls}=await run({analysis:{...analysis(),verifyCommands}});assert.equal(result.status,'aborted');assert.equal(calls.length,1);});
// Resume: checkpoints after analysis/baseline and each code-loop iteration (mirrors bug-fix).
const checkpoints=logs=>logs.filter(l=>l.startsWith('@@auto-recipe ')).map(l=>JSON.parse(l.slice('@@auto-recipe '.length))).filter(e=>e.kind==='checkpoint').map(e=>e.state);
const labels=calls=>calls.map(c=>c.label);
test('checkpoints follow analysis, baseline and every iteration; last records approval',async()=>{const f={id:'x',severity:'high',problem:'drift',requiredFix:'restore'};const {result,logs}=await run({'review-1':n=>n===1?{...review(),verdict:'NEEDS_REVISION',findings:[f]}:review()});assert.equal(result.status,'completed');const cps=checkpoints(logs);assert.ok(cps.length>=4);for(const s of cps){assert.equal(s.task,'Extract helper');assert.equal(s.repo,'/repo');assert.ok(Number.isInteger(s.round)&&s.round>=1);}assert.ok(cps.every(s=>s.analysis&&!Object.hasOwn(s,'setup')));assert.ok(cps.some(s=>s.analysis&&!s.baseline));assert.ok(cps.some(s=>s.baseline&&s.attemptCount===0));const one=cps.find(s=>s.attemptCount===1);assert.notEqual(one.approved,true);assert.deepEqual(one.lastFindings,[f]);const last=cps.at(-1);assert.equal(last.attemptCount,2);assert.equal(last.approved,true);});
test('resume after approval goes straight to validate',async()=>{const first=await run();const state=checkpoints(first.logs).at(-1);assert.equal(state.approved,true);const next=await run({},{resume:state});assert.equal(next.result.status,'completed');assert.deepEqual(labels(next.calls),['validate']);assert.deepEqual(next.result.changedPaths,['src.js']);});
test('resume from baseline checkpoint skips analysis and baseline',async()=>{const first=await run();const state=checkpoints(first.logs).find(s=>s.baseline&&s.attemptCount===0);const next=await run({},{resume:state});assert.equal(next.result.status,'completed');assert.deepEqual(labels(next.calls),['implement #1','review-1 #1','review-2 #1','validate']);});
test('resume from analysis checkpoint reruns baseline but not analysis',async()=>{const first=await run();const state=checkpoints(first.logs).find(s=>s.analysis&&!s.baseline);const next=await run({},{resume:state});assert.equal(next.result.status,'completed');assert.equal(labels(next.calls)[0],'baseline');assert.ok(!labels(next.calls).includes('analysis'));});
test('unapproved iteration checkpoint resumes at next iteration with its findings',async()=>{const f={id:'x',severity:'high',problem:'drift',requiredFix:'restore the API'};const first=await run({'review-1':n=>n===1?{...review(),verdict:'NEEDS_REVISION',findings:[f]}:review()});const state=checkpoints(first.logs).find(s=>s.attemptCount===1);const next=await run({},{resume:state});assert.equal(next.result.status,'completed');assert.equal(labels(next.calls)[0],'implement #2');assert.match(next.calls[0].prompt,/restore the API/);assert.equal(next.result.reviewTrail.length,2);});
for(const bad of [s=>({...s,task:'Other'}),s=>({...s,repo:'/other'}),s=>({...s,round:0}),s=>({...s,analysis:null}),s=>({...s,approved:true,baseline:null}),s=>({...s,attemptCount:4}),s=>({...s,changedPaths:['outside.js']})])test('invalid resume rejected '+bad.toString(),async()=>{const first=await run();const state=checkpoints(first.logs).at(-1);await assert.rejects(run({},{resume:bad(state)}));});
test('single implementer verification failure becomes a repair finding, not an abort',async()=>{const {result,calls}=await run({implement:n=>n===1?{...impl(),commands:[cmd(1)]}:impl()});assert.equal(result.status,'completed');assert.deepEqual(labels(calls).filter(l=>l.startsWith('implement')),['implement #1','implement #2']);assert.ok(!labels(calls).includes('review-1 #1'));assert.match(calls.find(c=>c.label==='implement #2').prompt,/implementer-verification/);assert.equal(result.reviewTrail[0].verdict,'NEEDS_REVISION');});
test('scope escape still aborts on the first iteration',async()=>{const {result,calls}=await run({implement:n=>n===1?{...impl(),changedPaths:['unknown.js']}:impl()});assert.equal(result.status,'aborted');assert.equal(calls.filter(c=>c.label.startsWith('implement')).length,1);});
test('exhausted repair budget offers a fresh-budget resume',async()=>{const {result}=await run({implement:{...impl(),commands:[cmd(1)]}});assert.equal(result.status,'aborted');assert.equal(result.resume.attemptCount,0);assert.equal(result.resume.task,'Extract helper');assert.ok(result.resume.baseline);});
